# https://travis-ci.org/#!/jleclanche/fireplace
sudo: false
language: python
python:
  - 3.4
script:
  - ./data/extras/enhance.py
  - cd tests
  - python test_main.py
notifications:
  email:
    on_failure: always
    on_success: change
  irc:
    channels:
      - "chat.freenode.net#hearthsim"
    use_notice: true
    skip_join: true
